# Generated by Django 6.0.4 on 2026-04-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Квантум'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_name',
            field=models.CharField(max_length=50, verbose_name='Направление'),
        ),
    ]
